-- ============================================================
-- RepChamp — Supabase Database Schema (FULL)
-- Run this in Supabase SQL Editor
-- ============================================================

-- 0. Extensions
create extension if not exists "pgcrypto";

-- ============================================================
-- 1. TABLES
-- ============================================================

-- 1a. Profiles (extends auth.users)
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  avatar_url text,
  level int default 1,
  xp int default 0,
  streak int default 0,
  created_at timestamptz default now()
);

-- 1b. Workout sessions (solo + duel mode)
create table if not exists workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  exercise_type text not null check (exercise_type in (
    'push_up', 'squat', 'crunch', 'pull_up', 'plank', 'lunge', 'shoulder_press'
  )),
  rep_count int not null,
  duration_seconds int,
  created_at timestamptz default now()
);

-- 1c. Duel rooms
create table if not exists duel_rooms (
  id uuid primary key default gen_random_uuid(),
  status text default 'waiting' check (status in ('waiting', 'active', 'finished')),
  exercise_type text not null check (exercise_type in (
    'push_up', 'squat', 'crunch', 'pull_up', 'plank', 'lunge', 'shoulder_press'
  )),
  duration_seconds int default 60,
  start_time timestamptz,
  winner_id uuid references profiles(id),
  created_at timestamptz default now()
);

-- 1d. Duel players (real-time rep tracking)
create table if not exists duel_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid references duel_rooms(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  reps int default 0,
  ready boolean default false,
  joined_at timestamptz default now(),
  unique(room_id, user_id)
);

-- 1e. Friendships (arkadas sistemi: istek gonderme/kabul/red)
create table if not exists friendships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  friend_id uuid references profiles(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);

-- 1f. Challenges (haftalik challenge sistemi)
create table if not exists weekly_challenges (
  id text primary key,
  type text not null check (type in ('rep_goal', 'time_trial', 'streak_days')),
  title text not null,
  description text,
  exercise_type text check (exercise_type in (
    'push_up', 'squat', 'crunch', 'pull_up', 'plank', 'lunge', 'shoulder_press'
  )),
  target_value int not null,
  xp_reward int default 500,
  start_date timestamptz not null,
  end_date timestamptz not null
);

-- 1g. Challenge progress (her kullanicinin challenge ilerlemesi)
create table if not exists challenge_progress (
  id uuid primary key default gen_random_uuid(),
  challenge_id text references weekly_challenges(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  progress int default 0,
  completed boolean default false,
  completed_at timestamptz,
  unique(challenge_id, user_id)
);

-- 1h. User achievements (kilitsiz basarimlar)
create table if not exists user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  achievement_id text not null check (achievement_id in (
    'first_rep', 'club_100', 'club_1000', 'streak_7', 'streak_30',
    'first_win', 'no_pain_no_gain', 'early_bird', 'night_owl',
    'comeback_king', 'perfect_form', 'speed_demon', 'duelist', 'veteran'
  )),
  unlocked_at timestamptz default now(),
  unique (user_id, achievement_id)
);

-- 1i. Streak history (gunluk antrenman kaydi)
create table if not exists streak_history (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  workout_date date not null,
  rep_count int default 0,
  xp_earned int default 0,
  unique (user_id, workout_date)
);

-- 1j. Friend requests log (arkadaslik istek gecmisi)
create table if not exists friend_requests (
  id bigint generated by default as identity primary key,
  from_user_id uuid references profiles(id) on delete cascade not null,
  to_user_id uuid references profiles(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz default now(),
  unique (from_user_id, to_user_id)
);

-- ============================================================
-- 2. INDEXES
-- ============================================================

create index if not exists idx_workout_sessions_user_id on workout_sessions(user_id);
create index if not exists idx_workout_sessions_created_at on workout_sessions(created_at desc);
create index if not exists idx_duel_rooms_status on duel_rooms(status);
create index if not exists idx_duel_players_room_id on duel_players(room_id);
create index if not exists idx_friendships_user_id on friendships(user_id);
create index if not exists idx_friendships_friend_id on friendships(friend_id);
create index if not exists idx_friendships_status on friendships(status);
create index if not exists idx_challenge_progress_user on challenge_progress(user_id);
create index if not exists idx_challenge_progress_challenge on challenge_progress(challenge_id);
create index if not exists idx_user_achievements_user on user_achievements(user_id);
create index if not exists idx_streak_history_user on streak_history(user_id, workout_date desc);
create index if not exists idx_friend_requests_to on friend_requests(to_user_id, status);
create index if not exists idx_friend_requests_from on friend_requests(from_user_id, status);

-- ============================================================
-- 3. ROW LEVEL SECURITY
-- ============================================================

-- 3a. Profiles
alter table profiles enable row level security;

create policy "Profiles are viewable by everyone"
  on profiles for select
  using (true);

create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

create policy "Users can insert their own profile"
  on profiles for insert
  with check (auth.uid() = id);

-- 3b. Workout sessions
alter table workout_sessions enable row level security;

create policy "Users can view their own workout sessions"
  on workout_sessions for select
  using (auth.uid() = user_id);

create policy "Users can insert their own workout sessions"
  on workout_sessions for insert
  with check (auth.uid() = user_id);

-- 3c. Duel rooms
alter table duel_rooms enable row level security;

create policy "Anyone can view duel rooms"
  on duel_rooms for select
  using (true);

create policy "Authenticated users can create duel rooms"
  on duel_rooms for insert
  with check (auth.role() = 'authenticated');

create policy "Participants can update duel rooms"
  on duel_rooms for update
  using (
    exists (
      select 1 from duel_players
      where room_id = duel_rooms.id
        and user_id = auth.uid()
    )
  );

-- 3d. Duel players
alter table duel_players enable row level security;

create policy "Participants can view duel players in their room"
  on duel_players for select
  using (
    exists (
      select 1 from duel_players dp
      where dp.room_id = duel_players.room_id
        and dp.user_id = auth.uid()
    )
  );

create policy "Users can join a duel room"
  on duel_players for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own duel player row"
  on duel_players for update
  using (auth.uid() = user_id);

-- 3e. Friendships
alter table friendships enable row level security;

create policy "Users can view their own friendships"
  on friendships for select
  using (auth.uid() = user_id or auth.uid() = friend_id);

create policy "Users can send friend requests"
  on friendships for insert
  with check (auth.uid() = user_id);

create policy "Users can update friendships they are involved in"
  on friendships for update
  using (auth.uid() = user_id or auth.uid() = friend_id);

-- 3f. Weekly challenges
alter table weekly_challenges enable row level security;

create policy "Challenges are viewable by everyone"
  on weekly_challenges for select
  using (true);

create policy "Only admins can insert challenges"
  on weekly_challenges for insert
  with check (auth.role() = 'service_role');

-- 3g. Challenge progress
alter table challenge_progress enable row level security;

create policy "Users can view their own challenge progress"
  on challenge_progress for select
  using (auth.uid() = user_id);

create policy "Users can insert their own challenge progress"
  on challenge_progress for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own challenge progress"
  on challenge_progress for update
  using (auth.uid() = user_id);

-- 3h. User achievements
alter table user_achievements enable row level security;

create policy "Users can view own achievements"
  on user_achievements for select
  using (auth.uid() = user_id);

create policy "Users can insert own achievements"
  on user_achievements for insert
  with check (auth.uid() = user_id);

-- 3i. Streak history
alter table streak_history enable row level security;

create policy "Users can view own streak history"
  on streak_history for select
  using (auth.uid() = user_id);

create policy "Users can insert own streak history"
  on streak_history for insert
  with check (auth.uid() = user_id);

-- 3j. Friend requests
alter table friend_requests enable row level security;

create policy "Users can view their own friend requests"
  on friend_requests for select
  using (auth.uid() = from_user_id or auth.uid() = to_user_id);

create policy "Users can send friend requests"
  on friend_requests for insert
  with check (auth.uid() = from_user_id);

create policy "Users can update requests they received"
  on friend_requests for update
  using (auth.uid() = to_user_id);

-- ============================================================
-- 4. STORAGE (Avatar yuklemeleri icin)
-- ============================================================

-- Bucket: avatars
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Avatar storage policy: herkes gorebilir
create policy "Avatar images are publicly accessible"
  on storage.objects for select
  using (bucket_id = 'avatars');

-- Avatar storage policy: kullanici kendi avatarini yukleyebilir
create policy "Users can upload their own avatar"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- ============================================================
-- 5. FUNCTIONS (RPC)
-- ============================================================

-- 5a. Leaderboard: top users by total reps
create or replace function get_leaderboard(limit_count int default 20)
returns table (
  user_id uuid,
  username text,
  avatar_url text,
  total_reps bigint,
  total_sessions bigint,
  level int,
  streak int
)
language sql
security definer
as $$
  select
    p.id,
    p.username,
    p.avatar_url,
    coalesce(sum(ws.rep_count), 0)::bigint as total_reps,
    count(ws.id)::bigint as total_sessions,
    p.level,
    p.streak
  from profiles p
  left join workout_sessions ws on ws.user_id = p.id
  group by p.id, p.username, p.avatar_url, p.level, p.streak
  order by total_reps desc
  limit limit_count;
$$;

-- 5b. Haftalik arkadas liderlik tablosu
create or replace function get_friend_leaderboard(user_id uuid, limit_count int default 20)
returns table (
  friend_id uuid,
  username text,
  total_reps bigint,
  level int,
  streak int
)
language sql
security definer
as $$
  select
    case when f.user_id = get_friend_leaderboard.user_id then f.friend_id else f.user_id end,
    p.username,
    coalesce(sum(ws.rep_count), 0)::bigint,
    p.level,
    p.streak
  from friendships f
  join profiles p on p.id = case when f.user_id = get_friend_leaderboard.user_id then f.friend_id else f.user_id end
  left join workout_sessions ws on ws.user_id = p.id
  where (f.user_id = get_friend_leaderboard.user_id or f.friend_id = get_friend_leaderboard.user_id)
    and f.status = 'accepted'
  group by p.id, p.username, p.level, p.streak
  order by total_reps desc
  limit limit_count;
$$;

-- 5c. Challenge siralamasi (challenge'da en cok rep yapanlar)
create or replace function get_challenge_leaderboard(challenge_id text, limit_count int default 20)
returns table (
  user_id uuid,
  username text,
  progress int,
  completed boolean
)
language sql
security definer
as $$
  select
    cp.user_id,
    p.username,
    cp.progress,
    cp.completed
  from challenge_progress cp
  join profiles p on p.id = cp.user_id
  where cp.challenge_id = get_challenge_leaderboard.challenge_id
  order by cp.progress desc
  limit limit_count;
$$;

-- ============================================================
-- 6. TRIGGERS
-- ============================================================

-- Auto-create profile on signup
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substr(new.id::text, 1, 8))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ============================================================
-- 7. REALTIME (Canli guncellemeler icin)
-- ============================================================

-- Duel odalari icin realtime aktif et
alter publication supabase_realtime add table duel_rooms;
alter publication supabase_realtime add table duel_players;
alter publication supabase_realtime add table challenge_progress;
