-- ============================================================
-- RepChamp — Supabase Database Schema (FULL)
-- Run this in Supabase SQL Editor
-- ============================================================

-- 0. Extensions
create extension if not exists "pgcrypto";

-- ============================================================
-- 1. TABLES
-- ============================================================

-- 1a. Profiles (extends auth.users)
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  avatar_url text,
  level int default 1,
  xp int default 0,
  streak int default 0,
  created_at timestamptz default now()
);

-- 1b. Workout sessions (solo + duel mode)
create table if not exists workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  exercise_type text not null check (exercise_type in (
    'push_up', 'squat', 'crunch', 'pull_up', 'plank', 'lunge', 'shoulder_press'
  )),
  rep_count int not null,
  duration_seconds int,
  xp_earned int default 0,
  created_at timestamptz default now()
);

-- 1c. Duel rooms
create table if not exists duel_rooms (
  id uuid primary key default gen_random_uuid(),
  status text default 'waiting' check (status in ('waiting', 'active', 'finished')),
  exercise_type text not null check (exercise_type in (
    'push_up', 'squat', 'crunch', 'pull_up', 'plank', 'lunge', 'shoulder_press'
  )),
  duration_seconds int default 60,
  start_time timestamptz,
  winner_id uuid references profiles(id),
  created_at timestamptz default now()
);

-- 1d. Duel players (real-time rep tracking)
create table if not exists duel_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid references duel_rooms(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  reps int default 0,
  ready boolean default false,
  joined_at timestamptz default now(),
  unique(room_id, user_id)
);

-- 1e. Friendships (arkadas sistemi: istek gonderme/kabul/red)
create table if not exists friendships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  friend_id uuid references profiles(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);

-- 1f. Challenges (haftalik challenge sistemi)
create table if not exists weekly_challenges (
  id text primary key,
  type text not null check (type in ('rep_goal', 'time_trial', 'streak_days')),
  title text not null,
  description text,
  exercise_type text check (exercise_type in (
    'push_up', 'squat', 'crunch', 'pull_up', 'plank', 'lunge', 'shoulder_press'
  )),
  target_value int not null,
  xp_reward int default 500,
  start_date timestamptz not null,
  end_date timestamptz not null
);

-- 1g. Challenge progress (her kullanicinin challenge ilerlemesi)
create table if not exists challenge_progress (
  id uuid primary key default gen_random_uuid(),
  challenge_id text references weekly_challenges(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  progress int default 0,
  completed boolean default false,
  completed_at timestamptz,
  unique(challenge_id, user_id)
);

-- 1h. User achievements (kilitsiz basarimlar)
create table if not exists user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  achievement_id text not null check (achievement_id in (
    'first_rep', 'club_100', 'club_1000', 'streak_7', 'streak_30',
    'first_win', 'no_pain_no_gain', 'early_bird', 'night_owl',
    'comeback_king', 'perfect_form', 'speed_demon', 'duelist', 'veteran'
  )),
  unlocked_at timestamptz default now(),
  unique (user_id, achievement_id)
);

-- 1i. Streak history (gunluk antrenman kaydi)
create table if not exists streak_history (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  workout_date date not null,
  rep_count int default 0,
  xp_earned int default 0,
  unique (user_id, workout_date)
);

-- 1j. Friend requests log (arkadaslik istek gecmisi)
create table if not exists friend_requests (
  id bigint generated by default as identity primary key,
  from_user_id uuid references profiles(id) on delete cascade not null,
  to_user_id uuid references profiles(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz default now(),
  unique (from_user_id, to_user_id)
);

-- ============================================================
-- 2. INDEXES
-- ============================================================

create index if not exists idx_workout_sessions_user_id on workout_sessions(user_id);
create index if not exists idx_workout_sessions_created_at on workout_sessions(created_at desc);
create index if not exists idx_duel_rooms_status on duel_rooms(status);
create index if not exists idx_duel_players_room_id on duel_players(room_id);
create index if not exists idx_friendships_user_id on friendships(user_id);
create index if not exists idx_friendships_friend_id on friendships(friend_id);
create index if not exists idx_friendships_status on friendships(status);
create index if not exists idx_challenge_progress_user on challenge_progress(user_id);
create index if not exists idx_challenge_progress_challenge on challenge_progress(challenge_id);
create index if not exists idx_user_achievements_user on user_achievements(user_id);
create index if not exists idx_streak_history_user on streak_history(user_id, workout_date desc);
create index if not exists idx_friend_requests_to on friend_requests(to_user_id, status);
create index if not exists idx_friend_requests_from on friend_requests(from_user_id, status);

-- ============================================================
-- 3. ROW LEVEL SECURITY
-- ============================================================

-- Schema grants (authenticated ve anon rollerine izin ver)
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- 3a. Profiles
alter table profiles enable row level security;

drop policy if exists "Profiles are viewable by everyone" on profiles;
create policy "Profiles are viewable by everyone"
  on profiles for select
  using (true);

drop policy if exists "Users can update their own profile" on profiles;
create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on profiles;
create policy "Users can insert their own profile"
  on profiles for insert
  with check (auth.uid() = id);

-- 3b. Workout sessions
alter table workout_sessions enable row level security;

drop policy if exists "Users can view their own workout sessions" on workout_sessions;
create policy "Users can view their own workout sessions"
  on workout_sessions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own workout sessions" on workout_sessions;
create policy "Users can insert their own workout sessions"
  on workout_sessions for insert
  with check (auth.uid() = user_id);

-- 3c. Duel rooms
alter table duel_rooms enable row level security;

drop policy if exists "Anyone can view duel rooms" on duel_rooms;
create policy "Anyone can view duel rooms"
  on duel_rooms for select
  using (true);

drop policy if exists "Authenticated users can create duel rooms" on duel_rooms;
create policy "Authenticated users can create duel rooms"
  on duel_rooms for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Participants can update duel rooms" on duel_rooms;
create policy "Participants can update duel rooms"
  on duel_rooms for update
  using (
    exists (
      select 1 from duel_players
      where room_id = duel_rooms.id
        and user_id = auth.uid()
    )
  );

-- 3d. Duel players
alter table duel_players enable row level security;

drop policy if exists "Participants can view duel players in their room" on duel_players;
create policy "Participants can view duel players in their room"
  on duel_players for select
  using (
    exists (
      select 1 from duel_players dp
      where dp.room_id = duel_players.room_id
        and dp.user_id = auth.uid()
    )
  );

drop policy if exists "Users can join a duel room" on duel_players;
create policy "Users can join a duel room"
  on duel_players for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own duel player row" on duel_players;
create policy "Users can update their own duel player row"
  on duel_players for update
  using (auth.uid() = user_id);

-- 3e. Friendships
alter table friendships enable row level security;

drop policy if exists "Users can view their own friendships" on friendships;
create policy "Users can view their own friendships"
  on friendships for select
  using (auth.uid() = user_id or auth.uid() = friend_id);

drop policy if exists "Users can send friend requests" on friendships;
create policy "Users can send friend requests"
  on friendships for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update friendships they are involved in" on friendships;
create policy "Users can update friendships they are involved in"
  on friendships for update
  using (auth.uid() = user_id or auth.uid() = friend_id);

-- 3f. Weekly challenges
alter table weekly_challenges enable row level security;

drop policy if exists "Challenges are viewable by everyone" on weekly_challenges;
create policy "Challenges are viewable by everyone"
  on weekly_challenges for select
  using (true);

drop policy if exists "Only admins can insert challenges" on weekly_challenges;
create policy "Only admins can insert challenges"
  on weekly_challenges for insert
  with check (auth.role() = 'service_role');

-- 3g. Challenge progress
alter table challenge_progress enable row level security;

drop policy if exists "Users can view their own challenge progress" on challenge_progress;
create policy "Users can view their own challenge progress"
  on challenge_progress for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own challenge progress" on challenge_progress;
create policy "Users can insert their own challenge progress"
  on challenge_progress for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own challenge progress" on challenge_progress;
create policy "Users can update their own challenge progress"
  on challenge_progress for update
  using (auth.uid() = user_id);

-- 3h. User achievements
alter table user_achievements enable row level security;

drop policy if exists "Users can view own achievements" on user_achievements;
create policy "Users can view own achievements"
  on user_achievements for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own achievements" on user_achievements;
create policy "Users can insert own achievements"
  on user_achievements for insert
  with check (auth.uid() = user_id);

-- 3i. Streak history
alter table streak_history enable row level security;

drop policy if exists "Users can view own streak history" on streak_history;
create policy "Users can view own streak history"
  on streak_history for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own streak history" on streak_history;
create policy "Users can insert own streak history"
  on streak_history for insert
  with check (auth.uid() = user_id);

-- 3j. Friend requests
alter table friend_requests enable row level security;

drop policy if exists "Users can view their own friend requests" on friend_requests;
create policy "Users can view their own friend requests"
  on friend_requests for select
  using (auth.uid() = from_user_id or auth.uid() = to_user_id);

drop policy if exists "Users can send friend requests" on friend_requests;
create policy "Users can send friend requests"
  on friend_requests for insert
  with check (auth.uid() = from_user_id);

drop policy if exists "Users can update requests they received" on friend_requests;
create policy "Users can update requests they received"
  on friend_requests for update
  using (auth.uid() = to_user_id);

-- ============================================================
-- 4. STORAGE (Avatar yuklemeleri icin)
-- ============================================================
-- Not: Bu kısım Supabase Storage eklentisi kurulu değilse çalışmaz.
-- Hata alırsan Supabase Dashboard > Storage'dan 'avatars' bucket'ını manuel oluştur.

do $$
begin
  -- Bucket: avatars
  insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true)
  on conflict (id) do nothing;

  -- Avatar storage policy: herkes gorebilir
  execute 'drop policy if exists "Avatar images are publicly accessible" on storage.objects';
  execute 'create policy "Avatar images are publicly accessible"
    on storage.objects for select
    using (bucket_id = ''avatars'')';

  -- Avatar storage policy: kullanici kendi avatarini yukleyebilir
  execute 'drop policy if exists "Users can upload their own avatar" on storage.objects';
  execute 'create policy "Users can upload their own avatar"
    on storage.objects for insert
    with check (
      bucket_id = ''avatars''
      and auth.uid()::text = (storage.foldername(name))[1]
    )';
exception when others then
  raise notice 'Storage section skipped: %', SQLERRM;
end;
$$;

-- ============================================================
-- 5. FUNCTIONS (RPC)
-- ============================================================

-- 5a. Leaderboard: top users by total XP
create or replace function get_leaderboard(limit_count int default 20)
returns table (
  user_id uuid,
  username text,
  avatar_url text,
  total_reps bigint,
  total_sessions bigint,
  level int,
  streak int,
  xp int
)
language sql
security definer
as $$
  select
    p.id,
    p.username,
    p.avatar_url,
    coalesce(sum(ws.rep_count), 0)::bigint as total_reps,
    count(ws.id)::bigint as total_sessions,
    p.level,
    p.streak,
    p.xp
  from profiles p
  left join workout_sessions ws on ws.user_id = p.id
  group by p.id, p.username, p.avatar_url, p.level, p.streak, p.xp
  order by p.xp desc
  limit limit_count;
$$;

-- 5c. Get current user's rank and total user count for leaderboard footer
create or replace function get_user_rank(target_user_id uuid)
returns table (rank bigint, total_count bigint, total_xp int)
language sql
security definer
as $$
  with ranked as (
    select id, xp, row_number() over (order by xp desc) as pos
    from profiles
  )
  select
    (select pos from ranked where id = target_user_id) as rank,
    (select count(*) from profiles)::bigint as total_count,
    (select xp from ranked where id = target_user_id) as total_xp;
$$;

-- 5b. Haftalik arkadas liderlik tablosu
create or replace function get_friend_leaderboard(user_id uuid, limit_count int default 20)
returns table (
  friend_id uuid,
  username text,
  total_reps bigint,
  level int,
  streak int
)
language sql
security definer
as $$
  select
    distinct on (p.id)
    p.id,
    p.username,
    coalesce(sum(ws.rep_count) filter (where ws.user_id = p.id), 0)::bigint as total_reps,
    p.level,
    p.streak
  from friendships f
  join profiles p on p.id in (f.user_id, f.friend_id)
  left join workout_sessions ws on ws.user_id = p.id
  where (f.user_id = get_friend_leaderboard.user_id or f.friend_id = get_friend_leaderboard.user_id)
    and f.status = 'accepted'
    and p.id <> get_friend_leaderboard.user_id
  group by p.id, p.username, p.level, p.streak
  order by p.id, total_reps desc
  limit limit_count;
$$;

-- 5c. Challenge siralamasi (challenge'da en cok rep yapanlar)
create or replace function get_challenge_leaderboard(challenge_id text, limit_count int default 20)
returns table (
  user_id uuid,
  username text,
  progress int,
  completed boolean
)
language sql
security definer
as $$
  select
    cp.user_id,
    p.username,
    cp.progress,
    cp.completed
  from challenge_progress cp
  join profiles p on p.id = cp.user_id
  where cp.challenge_id = get_challenge_leaderboard.challenge_id
  order by cp.progress desc
  limit limit_count;
$$;

-- ============================================================
-- 6. TRIGGERS
-- ============================================================

-- Auto-create profile on signup
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, xp, level)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substr(new.id::text, 1, 8)),
    100,
    1
  );
  return new;
end;
$$;

-- 5d. Add/remove XP from a user (for duel results) + auto level-up
create or replace function add_xp(target_user_id uuid, xp_amount int)
returns void
language plpgsql
security definer
as $$
begin
  update profiles
  set
    xp = greatest(0, xp + xp_amount),
    level = greatest(1, floor((greatest(0, xp + xp_amount)) / 1000) + 1)
  where id = target_user_id;
end;
$$;

-- 5e. Get daily stats for a user (today's total reps and XP)
create or replace function get_daily_stats(target_user_id uuid)
returns table (total_reps bigint, total_xp bigint)
language sql
security definer
as $$
  select
    coalesce(sum(ws.rep_count), 0)::bigint as total_reps,
    coalesce(sum(ws.xp_earned), 0)::bigint as total_xp
  from workout_sessions ws
  where ws.user_id = target_user_id
    and ws.created_at >= current_date::timestamptz;
$$;

-- 5f. Get weekly XP breakdown per day for the current week
create or replace function get_weekly_breakdown(target_user_id uuid)
returns table (day_index int, total_xp bigint)
language sql
security definer
as $$
  select
    extract(dow from ws.created_at)::int as day_index,
    coalesce(sum(ws.xp_earned), 0)::bigint as total_xp
  from workout_sessions ws
  where ws.user_id = target_user_id
    and ws.created_at >= date_trunc('week', current_date)::timestamptz
  group by extract(dow from ws.created_at)
  order by day_index;
$$;

-- 5g. Get weekly total XP
create or replace function get_weekly_xp(target_user_id uuid)
returns int
language sql
security definer
as $$
  select coalesce(sum(ws.xp_earned), 0)::int
  from workout_sessions ws
  where ws.user_id = target_user_id
    and ws.created_at >= date_trunc('week', current_date)::timestamptz;
$$;

-- 5h. Get recent activity for a user
create or replace function get_recent_activity(target_user_id uuid, limit_count int default 10)
returns table (
  exercise_type text,
  rep_count int,
  xp_earned int,
  duration_seconds int,
  created_at timestamptz
)
language sql
security definer
as $$
  select ws.exercise_type, ws.rep_count, ws.xp_earned, ws.duration_seconds, ws.created_at
  from workout_sessions ws
  where ws.user_id = target_user_id
  order by ws.created_at desc
  limit limit_count;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- 5i. Profile duel stats (total duels, wins, losses, win rate)
create or replace function get_profile_duel_stats(target_user_id uuid)
returns table (total_duels bigint, wins bigint, losses bigint, win_rate numeric)
language sql
security definer
as $$
  with duel_counts as (
    select
      count(*)::bigint as total,
      count(*) filter (where dr.winner_id = target_user_id)::bigint as w
    from duel_rooms dr
    join duel_players dp on dp.room_id = dr.id and dp.user_id = target_user_id
    where dr.status = 'finished'
  )
  select
    total,
    w,
    (total - w)::bigint as losses,
    case when total > 0 then round((w::numeric / total) * 100, 1) else 0 end
  from duel_counts;
$$;

-- 5j. Recent duels with opponent info
create or replace function get_recent_duels(target_user_id uuid, limit_count int default 20)
returns table (
  room_id uuid,
  exercise_type text,
  opponent_username text,
  opponent_avatar_url text,
  won boolean,
  created_at timestamptz
)
language sql
security definer
as $$
  select
    dr.id,
    dr.exercise_type,
    op.username,
    op.avatar_url,
    dr.winner_id = target_user_id,
    dr.created_at
  from duel_rooms dr
  join duel_players dp1 on dp1.room_id = dr.id and dp1.user_id = target_user_id
  join duel_players dp2 on dp2.room_id = dr.id and dp2.user_id <> target_user_id
  join profiles op on op.id = dp2.user_id
  where dr.status = 'finished'
  order by dr.created_at desc
  limit limit_count;
$$;

-- 5k. Total reps across all workout sessions
create or replace function get_total_reps(target_user_id uuid)
returns table (total_reps bigint)
language sql
security definer
as $$
  select coalesce(sum(rep_count), 0)::bigint
  from workout_sessions
  where user_id = target_user_id;
$$;

-- 5l. Get user achievements with metadata
create or replace function get_user_achievements(target_user_id uuid)
returns table (
  achievement_id text,
  unlocked boolean,
  unlocked_at timestamptz
)
language sql
security definer
as $$
  select
    ach_id.achievement_id,
    ua.id is not null as unlocked,
    ua.unlocked_at
  from (
    values
      ('first_rep'), ('club_100'), ('club_1000'), ('streak_7'), ('streak_30'),
      ('first_win'), ('no_pain_no_gain'), ('early_bird'), ('night_owl'),
      ('comeback_king'), ('perfect_form'), ('speed_demon'), ('duelist'), ('veteran')
  ) as ach_id(achievement_id)
  left join user_achievements ua
    on ua.achievement_id = ach_id.achievement_id
    and ua.user_id = target_user_id;
$$;

-- ============================================================
-- 7. REALTIME (Canli guncellemeler icin)
-- ============================================================

-- Duel odalari icin realtime aktif et
do $$
begin
  alter publication supabase_realtime add table duel_rooms;
exception when others then raise notice 'duel_rooms zaten publication içinde';
end;
$$;

do $$
begin
  alter publication supabase_realtime add table duel_players;
exception when others then raise notice 'duel_players zaten publication içinde';
end;
$$;

do $$
begin
  alter publication supabase_realtime add table challenge_progress;
exception when others then raise notice 'challenge_progress zaten publication içinde';
end;
$$;
